version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "08:20"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
